app/urls.py
from django.urls import path , include
from app import views
from .views import *
urlpatterns = [
    path('', HomeView.as_view() , name='Items'),
    path('product-detail/<slug>/', ItemDetailView.as_view() , name='product-detail'),
    path('add-to-cart/<slug>/', add_to_cart , name='add-to-cart'),
    path('order-summary/', OrderSummaryView.as_view() , name='order-summary'),
    path('remove-from-cart/<slug>/', remove_from_cart , name='remove-from-cart'),
    path('remove_single_item_from_cart/<slug>/', remove_single_item_from_cart , name='remove_single_item_from_cart'),
    path('checkout/', views.checkout , name='checkout'),
]

pharmacy/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('app.urls')),

]

app/models.py
from pydoc import describe
from sre_parse import CATEGORIES
from tracemalloc import get_object_traceback
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
# Create your models here.

Category_Choice =(
    ('Tablets','Tablets'),
    ('Capsules','Capsule'),
    ('Injections','Injections'),
    
)
Label_Choice =(
    ('P','primary'),
    ('S','secondary'),
    ('D','danger'),
    
)

class Item(models.Model):
    title = models.CharField( max_length=50)
    price =models.FloatField()
    discount_price =models.FloatField(blank=True,null=True)
    category = models.CharField(choices=Category_Choice, max_length=15)
    label = models.CharField(choices=Label_Choice, max_length=15)
    slug = models.SlugField()
    description= models.TextField()

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("app:product-detail", kwargs={"slug": self.slug})
    
    
    
    def get_add_to_cart(self):
        return reverse("app:add-to-cart", kwargs={"slug": self.slug})
    
   
   
    def get_remove_from_cart(self):
        return reverse("app:remove-from-cart", kwargs={"slug": self.slug})
    




class OrderItem(models.Model):
    user= models.ForeignKey( settings.AUTH_USER_MODEL,on_delete=models.CASCADE )
    item=models.ForeignKey(Item, on_delete=models.CASCADE)
    ordered=models.BooleanField(default=False)  
    quantity=models.IntegerField(default=1)



    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    
    def get_total_price(self):
        return self.quantity * self.item.price
    
    
    
    def get_discount_price(self):
        return self.quantity * self.item.discount_price
    
    
    def get_saved_price(self):
        return self.get_total_price() - self.get_discount_price()
    
    
    def get_final_price(self):
        if self.get_discount_price():
            return self.get_discount_price()
        
        return self.get_total_price()


class Order(models.Model):
    user= models.ForeignKey( settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    items=models.ManyToManyField(OrderItem)
    ordered=models.BooleanField(default=False)  
    start_date = models.DateTimeField( auto_now_add=True) 
    ordered_date = models.DateTimeField() 
    
    
    def __str__(self):
        return self.user.username
    
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total    
        
    
    
    
        
    

    
     
     
    

app/views.py
import imp
from importlib.resources import contents
from multiprocessing import context
from django.contrib import messages
from django.shortcuts import render , get_object_or_404 , redirect
from .models import *
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import ListView , DetailView , View
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
app_name='app'


class HomeView(ListView):
    model = Item
    paginate_by= 8
    template_name = "home-page.html"


class ItemDetailView(DetailView):
    model = Item
    template_name = "product-page.html"


login_required
def checkout(request):
    return render(request,"checkout-page.html")

login_required
def add_to_cart(request,slug):
    item = get_object_or_404(Item,slug=slug)
    order_item ,created= OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False
        )
    order_qs=Order.objects.filter(user=request.user,ordered=False)
    
    if order_qs.exists():
        order=order_qs[0]
        if order.items.filter(item__slug=slug ).exists():
            
            order_item.quantity +=1
            order_item.save()
            messages.info(request,"This Item quantity was Updated.")
            return redirect('app:order-summary')
        else:
            messages.info(request,"This Item was added to your Cart.")
            order.items.add(order_item)
            return redirect('app:product-detail',slug=slug)
    else:
        ordered_date=timezone.now()
        order=Order.objects.create(user=request.user,ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request,"This Item was added to your Cart.")
        return redirect('app:product-detail',slug=slug)
    return redirect('app:product-detail',slug=slug)   
            
        
        
def remove_from_cart(request , slug):
    item =get_object_or_404(Item,slug=slug)
    order_qs=Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False,
            )[0]
            order.items.remove(order_item)
            messages.info(request,"This Item was removed from your Cart.")
            return redirect('app:order-summary')
        else:
            messages.info(request,"This Item was not in your Cart.")
            return redirect('app:product-detail',slug=slug)    
            
            
    else:
        messages.info(request,"You do not have an active order.")
        return redirect('app:product-detail',slug=slug)
    
    
    return redirect('app:product-detail',slug=slug)


def remove_single_item_from_cart(request , slug):
    item =get_object_or_404(Item,slug=slug)
    order_qs=Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False,
            )[0]
            if order_item.quantity > 1:
                
                order_item.quantity -=1
                order_item.save()
            
            else:
                order.items.remove(order_item)
            messages.info(request,"This Item quantity was updated.")

        else:
            messages.info(request,"This Item was not in your Cart.")
            return redirect('app:order-summary')    
            
            
    else:
        messages.info(request,"You do not have an active order.")
        return redirect('app:order-summary')
    
    
    return redirect('app:order-summary')
           
            
            
class OrderSummaryView(LoginRequiredMixin ,View):
    def get(self ,*args, **kwargs):
        
        try:
            order=Order.objects.get(user=self.request.user ,ordered=False)
            context={
                'object':order
            }
            return render(self.request,"order_summary.html",context)
        except ObjectDoesNotExist:
            messages.error(self.request,"You Don't have an active order"  )
            return redirect('/')    
    

templates/base.html
{% load static %}
{% load cart_template_tag %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}{% endblock title %}</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <title>{% block head_title %}{% endblock %}</title>






  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    


  </style>
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/" >
        <strong class="blue-text">Pharmacy</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links --> 
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout/" >Checkout</a>
          </li>
         
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
         
          <li class="nav-item">
            <a href="" class="nav-link waves-effect" target="_blank">
              <i class="fab fa-facebook-f"></i>
            </a>
          </li>
          <li class="nav-item">
            <a href="" class="nav-link waves-effect" target="_blank">
              <i class="fab fa-twitter"></i>
            </a>
          </li>

          {% comment %} cart {% endcomment %}
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'app:order-summary' %}" class="waves-effect nav-link border border-light rounded waves-effect"
             >
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item ml-2">
            <a href="{% url 'account_logout' %}" class="waves-effect nav-link border border-light rounded waves-effect">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
         {% else %}
          <li class="nav-item">
            <a href="{% url 'account_login' %}" class="waves-effect nav-link border border-light rounded waves-effect">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item ml-2">
            <a href="{% url 'account_signup' %}" class="waves-effect nav-link border border-light rounded waves-effect">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
         {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

    {% if messages %}
      {% for message in messages %}
      <div class="alert alert-warning alert-dismissible fade show" style="margin-top: 68px;" role="alert">
        <strong>Hi!</strong> {{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
    {% endif %}

  {% block content %}
  
  
  {% endblock content %}


   <!--Footer-->
   <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    {% comment %}<div class="pt-4">
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/docs/jquery/getting-started/download/" target="_blank"
        role="button">Download MDB
        <i class="fas fa-download ml-2"></i>
      </a>
      <a class="btn btn-outline-white" href="#" target="_blank" role="button">Start
        free tutorial
        <i class="fas fa-graduation-cap ml-2"></i>
      </a>
    </div>{% endcomment %}
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2022 Copyright:
      <a href="#" target="_blank"> ITZ-Solutions </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>

  
</body>

</html>

templates/home-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!--Carousel Wrapper-->
  {% comment %}<div id="carousel-example-1z"
       class="carousel slide carousel-fade pt-4"
       data-ride="carousel">
    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->
    <!--Slides-->
    <div class="carousel-inner" role="listbox">
      <!--First slide-->
      <div class="carousel-item active">
        <div class="view"
             style="background-image: url('{% static '/img/background1.jpg/' %}'); background-repeat: no-repeat; background-size: cover;">
          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Some Quotes</strong>
              </h1>
              <p>
                <strong>Some Useful Information</strong>
              </p>
            </div>
            <!-- Content -->
          </div>
          <!-- Mask & flexbox options-->
        </div>
      </div>
      <!--/First slide-->
      <!--Second slide-->
      <div class="carousel-item">
        <div class="view"
             style="background-image: url('{% static '/img/background2.jpg/' %}'); background-repeat: no-repeat; background-size: cover;">
          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Some Quotes</strong>
              </h1>
              <p>
                <strong>Some Useful Information</strong>
              </p>
            </div>
            <!-- Content -->
          </div>
          <!-- Mask & flexbox options-->
        </div>
      </div>
      <!--/Second slide-->
      <!--Third slide-->
      <div class="carousel-item">
        <div class="view"
             style="background-image: url('{% static '/img/background3.jpg/' %}'); background-repeat: no-repeat; background-size: cover;">
          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Some Quotes</strong>
              </h1>
              <p>
                <strong>Some Useful Information</strong>
              </p>
            </div>
            <!-- Content -->
          </div>
          <!-- Mask & flexbox options-->
        </div>
      </div>
      <!--/Third slide-->
    </div>
    <!--/.Slides-->
    <!--Controls-->
    <a class="carousel-control-prev"
       href="#carousel-example-1z"
       role="button"
       data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next"
       href="#carousel-example-1z"
       role="button"
       data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->
  </div>{% endcomment %}
  <!--/.Carousel Wrapper-->
  <!--Main layout-->
  <main>
    <div class="container">
      <!--Navbar-->
      <nav style="margin-top:80px;" class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mb-5">
        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>
        <!-- Collapse button -->
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#basicExampleNav"
                aria-controls="basicExampleNav"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav"> 
          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
          </ul>
          <!-- Links -->
          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2"
                     type="text"
                     placeholder="Search"
                     aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->
      </nav>
      <!--/.Navbar-->
      <!--Section: Products v.3-->
      <section class="text-center mb-4">
        <!--Grid row-->
        <div class="row wow fadeIn">
          <!--Grid column-->
          {% for item  in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">
            <!--Card-->
            <div class="card">
              <!--Card image-->
              <div class="view overlay">
                <img src="https://www.advancedsciencenews.com/wp-content/uploads/2022/05/A-pile-of-pills.jpg"
                     class="card-img-top"
                     alt="">
                <a href="{{item.get_absolute_url}}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->
              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{item.get_category_display}}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{item.get_absolute_url}}" class="dark-grey-text">{{item.title}}
                      <span class="badge badge-pill {{item.get_label_display}}-color">NEW</span>
                    </a>
                  </strong>
                </h5>
                <h4 class="font-weight-bold blue-text">
                  <strong>Rs
                    {% if item.discount_price %}
                    {{item.discount_price}}
                    {% else %}
                    {{item.price}}
                    {% endif %}
                  </strong>
                </h4>
              </div>
              <!--Card content-->
            </div>
            <!--Card-->
          </div>
          {% endfor %}
          <!--Grid column-->
          </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->
      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">
          {% if page_obj.has_previous %}
          <!--Arrow left-->
          <li class="page-item ">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}
          <li class="page-item active">
            <a class="page-link" href="?page={{page_obj.number}}">{{page_obj.number}}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      <!--Pagination-->
    </div>
  </main>
  <!--Main layout-->
{% endblock content %}

templates/order_summary.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class='container'>
    <div class="table-responsive text-nowrap ">
        <h1 style="margin-top:100px;">Order Summary</h1>
        <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Item title</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total Price</th>
              </tr>
            </thead>
            <tbody>
                {% for item in object.items.all %}
              <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{item.item.title}}</td>
                <td>{{item.item.price}}</td>
                <td><a href="{% url 'app:remove_single_item_from_cart' item.item.slug %}"><i class="fas fa-minus mr-2"></i></a><span class="badge badge-primary" >{{item.quantity}}</span>
                  <a href="{% url 'app:add-to-cart' item.item.slug %}"><i class="fas fa-plus ml-2"></i></a></td>
                <td>

                  {% if item.get_discount_price %}
                  Rs-{{item.get_discount_price}}
                  <span class="badge badge-primary">(Saving Rs {{item.get_saved_price}})</span>

                  {% else %}
                  Rs-{{item.get_total_price}}

                  {% endif %}
                  <a style="color: red;" class="float-right" href="{% url 'app:remove-from-cart' item.item.slug %}"><i class="fas fa-trash"></i></a>

                </td>
              </tr>
              {% empty %}
              <tr>

                <td colspan='5'>
                  Your Cart Is Empty.
                </td>
              </tr>
              <tr>

                <td colspan='5'>
                  <a href="/" class="btn btn-secondary float-right ">Continue Shopping</a>
                </td>
              </tr>
              {% endfor %}
              {% if object.get_total %}
              <tr>

                <td colspan='4'><b>Order Price</b></td>
                <td><b>{{object.get_total}}</b></td>
              </tr>
             
              <tr>

                <td colspan='5'>
                  <a href="/checkout/" class="btn btn-primary float-right ml-3">Proceed to Checkout</a>
                  <a href="/" class="btn btn-secondary float-right ">Continue Shopping</a>
                </td>
              </tr>
              {% endif %}
            </tbody>
          </table>
      </div>
</div>

{% endblock  %}

templates/product-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="https://www.advancedsciencenews.com/wp-content/uploads/2022/05/A-pile-of-pills.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{object.get_category_display}}</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">New</span>
              </a>
              <a href="">
                <span class="badge red mr-1">Bestseller</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span>
                <del>Rs{{object.price}}</del>
              </span>
              <span>Rs{{object.discount_price}}</span>
              {% else %}
              <span>{{object.price}}<span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{object.description}}</p>

            {% comment %}<form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              

            </form>{% endcomment %}
            <a href={{ object.get_add_to_cart }} class="btn btn-primary btn-md my-0 p"  >Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>

              
            </a>
     

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://www.advancedsciencenews.com/wp-content/uploads/2022/05/A-pile-of-pills.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://www.advancedsciencenews.com/wp-content/uploads/2022/05/A-pile-of-pills.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://www.advancedsciencenews.com/wp-content/uploads/2022/05/A-pile-of-pills.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

 
 
  {% endblock content %}